import * as tf from '@tensorflow/tfjs'
import fs from 'fs'
import path from 'path'
import { cholesky } from '../../../src/math/linalg'
import { expectClose, expectTensorClose } from '../../helpers/tolerance'

// Load PyTorch reference data (generated by scripts/generate-cholesky-reference.py)
const refPath = path.join(__dirname, '../../reference-data/cholesky-reference.json')
let refData = null
try {
  refData = JSON.parse(fs.readFileSync(refPath, 'utf-8'))
} catch (e) {
  // Reference data not available — reference tests will skip
}

describe('math/cholesky', () => {
  // ─── Forward tests vs PyTorch ─────────────────────────────────

  describe('forward (vs PyTorch reference)', () => {
    const forwardCases = refData ? refData.cholesky_forward : []

    for (const ref of forwardCases) {
      test(ref.name, () => {
        const L = cholesky(ref.A)
        const expected = tf.tensor(ref.L)
        expectTensorClose(L, expected, { rtol: 1e-5, atol: 1e-6 })
        L.dispose(); expected.dispose()
      })
    }

    test('roundtrip L·Lᵀ ≈ A', () => {
      const X = tf.tensor2d([
        [1.2, 0.5, -0.3],
        [0.5, 2.1, 0.7],
        [-0.3, 0.7, 1.5]
      ])
      const A = tf.add(tf.matMul(X, X, false, true), tf.mul(tf.eye(3), 0.1))
      const L = cholesky(A)
      const reconstructed = tf.matMul(L, L, false, true)
      expectTensorClose(reconstructed, A, { rtol: 1e-4, atol: 1e-4 })
      L.dispose(); X.dispose(); A.dispose(); reconstructed.dispose()
    })

    test('batched [2, 3, 3]', () => {
      const batch = tf.tensor([
        [[4, 2, 0], [2, 5, 1], [0, 1, 3]],
        [[9, 3, 0], [3, 5, 1], [0, 1, 2]]
      ])
      const L = cholesky(batch)
      expect(L.shape).toEqual([2, 3, 3])
      const reconstructed = tf.matMul(L, L, false, true)
      expectTensorClose(reconstructed, batch, { rtol: 1e-4, atol: 1e-4 })
      L.dispose(); batch.dispose(); reconstructed.dispose()
    })

    test('higher-rank batch [1, 2, 2, 2, 2]', () => {
      const A = tf.tensor([
        [
          [[[4, 1], [1, 3]], [[2, 0.5], [0.5, 2]]],
          [[[5, 2], [2, 4]], [[3, 1], [1, 2]]]
        ]
      ])
      const L = cholesky(A)
      expect(L.shape).toEqual([1, 2, 2, 2, 2])
      const reconstructed = tf.matMul(L, L, false, true)
      expectTensorClose(reconstructed, A, { rtol: 1e-4, atol: 1e-4 })
      L.dispose(); A.dispose(); reconstructed.dispose()
    })

    test('result is lower triangular', () => {
      const A = tf.tensor2d([[4, 2], [2, 3]])
      const L = cholesky(A)
      expect(L.arraySync()[0][1]).toBe(0)
      L.dispose(); A.dispose()
    })

    test('accepts JS array', () => {
      const L = cholesky([[4, 2], [2, 3]])
      expect(L.shape).toEqual([2, 2])
      expectClose(L.dataSync()[0], 2.0, { atol: 1e-6 })
      L.dispose()
    })

    test('jitter on near-singular', () => {
      const A = tf.tensor2d([[1, 0.9999], [0.9999, 1]])
      const L = cholesky(A, { jitter: 1e-4 })
      expect(L.shape).toEqual([2, 2])
      L.dispose(); A.dispose()
    })
  })

  // ─── Error cases ───────────────────────────────────────────────

  describe('errors', () => {
    test('throws on 1D', () => {
      expect(() => cholesky(tf.tensor1d([1, 2, 3]))).toThrow('2D')
    })
    test('throws on non-square', () => {
      expect(() => cholesky(tf.tensor2d([[1, 2, 3], [4, 5, 6]]))).toThrow('square')
    })
    test('throws on non-PD', () => {
      expect(() => cholesky(tf.tensor2d([[1, 2], [2, 1]]))).toThrow('not positive definite')
    })
    test('throws on singular', () => {
      expect(() => cholesky(tf.tensor2d([[1, 1], [1, 1]]))).toThrow('not positive definite')
    })
  })

  // ─── Memory ────────────────────────────────────────────────────

  describe('memory', () => {
    test('forward does not leak', () => {
      const A = tf.tensor2d([[4, 2], [2, 3]])
      const before = tf.memory().numTensors
      const L = cholesky(A)
      L.dispose()
      expect(tf.memory().numTensors).toBe(before)
      A.dispose()
    })
  })

  // ─── Gradient tests vs PyTorch ─────────────────────────────────

  describe('gradient: sum(L) vs PyTorch', () => {
    const cases = refData
      ? refData.cholesky_gradients.filter(c => c.loss_type === 'sum')
      : []

    for (const ref of cases) {
      test(ref.name, () => {
        const A = tf.tensor2d(ref.A)
        const dA = tf.grad(a => cholesky(a).sum())(A)
        const expected = tf.tensor2d(ref.grad)
        expectTensorClose(dA, expected, { rtol: 1e-3, atol: 1e-4 })
        dA.dispose(); A.dispose(); expected.dispose()
      })
    }
  })

  describe('gradient: sum(L²) vs PyTorch', () => {
    const cases = refData
      ? refData.cholesky_gradients.filter(c => c.loss_type === 'sum_sq')
      : []

    for (const ref of cases) {
      test(ref.name, () => {
        const A = tf.tensor2d(ref.A)
        const dA = tf.grad(a => cholesky(a).square().sum())(A)
        const expected = tf.tensor2d(ref.grad)
        expectTensorClose(dA, expected, { rtol: 1e-3, atol: 5e-4 })
        dA.dispose(); A.dispose(); expected.dispose()
      })
    }
  })

  describe('gradient: sum(log(diag(L))) vs PyTorch', () => {
    const cases = refData
      ? refData.cholesky_gradients.filter(c => c.loss_type === 'log_diag')
      : []

    for (const ref of cases) {
      test(ref.name, () => {
        const n = ref.A.length
        const A = tf.tensor2d(ref.A)
        const dA = tf.grad(a => {
          const L = cholesky(a)
          // Use L * eye to extract diagonal (bandPart has broken grad in TF.js)
          const diagL = tf.mul(L, tf.eye(n))
          return tf.sum(tf.log(tf.add(tf.abs(diagL), 1e-30)))
        })(A)
        const expected = tf.tensor2d(ref.grad)
        expectTensorClose(dA, expected, { rtol: 5e-2, atol: 1e-3 })
        dA.dispose(); A.dispose(); expected.dispose()
      })
    }
  })

  describe('gradient: frobenius(L) vs PyTorch', () => {
    const cases = refData
      ? refData.cholesky_gradients.filter(c => c.loss_type === 'frobenius')
      : []

    for (const ref of cases) {
      test(ref.name, () => {
        const A = tf.tensor2d(ref.A)
        const dA = tf.grad(a => tf.sqrt(cholesky(a).square().sum()))(A)
        const expected = tf.tensor2d(ref.grad)
        expectTensorClose(dA, expected, { rtol: 1e-3, atol: 1e-4 })
        dA.dispose(); A.dispose(); expected.dispose()
      })
    }
  })

  describe('gradient: structural', () => {
    test('gradient is symmetric', () => {
      const A = tf.tensor2d([[4, 2], [2, 3]])
      const dA = tf.grad(a => cholesky(a).sum())(A)
      const data = dA.arraySync()
      expectClose(data[0][1], data[1][0], { rtol: 1e-5, atol: 1e-6 })
      dA.dispose(); A.dispose()
    })

    test('gradient flows through upstream chain', () => {
      const params = tf.tensor2d([[1.0, 0.5], [0.5, 1.2]])
      const dp = tf.grad(p => {
        const sp = tf.softplus(p)
        const sym = tf.div(tf.add(sp, tf.transpose(sp)), 2)
        const pd = tf.add(sym, tf.eye(2))
        return cholesky(pd).sum()
      })(params)
      expect(dp.shape).toEqual([2, 2])
      const hasNonZero = Array.from(dp.dataSync()).some(v => Math.abs(v) > 1e-6)
      expect(hasNonZero).toBe(true)
      dp.dispose(); params.dispose()
    })

    test('batched gradient [2, 2, 2]', () => {
      const A = tf.tensor([
        [[4, 1], [1, 3]],
        [[9, 3], [3, 5]]
      ])
      const dA = tf.grad(a => cholesky(a).sum())(A)
      expect(dA.shape).toEqual([2, 2, 2])
      const data = dA.arraySync()
      expectClose(data[0][0][1], data[0][1][0], { rtol: 1e-4, atol: 1e-5 })
      expectClose(data[1][0][1], data[1][1][0], { rtol: 1e-4, atol: 1e-5 })
      dA.dispose(); A.dispose()
    })

    test('jitter gradient is finite on near-singular', () => {
      const A = tf.tensor2d([[1, 0.999], [0.999, 1]])
      const dA = tf.grad(a => cholesky(a, { jitter: 1e-3 }).sum())(A)
      const allFinite = Array.from(dA.dataSync()).every(v => isFinite(v))
      expect(allFinite).toBe(true)
      dA.dispose(); A.dispose()
    })

    test('gradient does not leak tensors', () => {
      const A = tf.tensor2d([[4, 2], [2, 3]])
      const before = tf.memory().numTensors
      const dA = tf.grad(a => cholesky(a).sum())(A)
      dA.dispose()
      expect(tf.memory().numTensors).toBe(before)
      A.dispose()
    })
  })

  // ─── Numerical gradient cross-check ────────────────────────────
  // These are secondary — PyTorch tests above are the ground truth.

  describe('gradient: numerical cross-check', () => {
    test('2x2 finite-diff matches analytic', () => {
      const A = tf.tensor2d([[4, 2], [2, 3]])
      const f = a => cholesky(a).sum()
      const analytic = tf.grad(f)(A)
      const numerical = numericalGrad(f, A)
      expectTensorClose(analytic, numerical, { rtol: 1e-3, atol: 1e-4 })
      analytic.dispose(); numerical.dispose(); A.dispose()
    })

    test('3x3 finite-diff matches analytic', () => {
      const A = tf.tensor2d([[25, 15, -5], [15, 18, 0], [-5, 0, 11]])
      const f = a => cholesky(a).sum()
      const analytic = tf.grad(f)(A)
      const numerical = numericalGrad(f, A)
      expectTensorClose(analytic, numerical, { rtol: 1e-3, atol: 1e-4 })
      analytic.dispose(); numerical.dispose(); A.dispose()
    })
  })
})

// ─── Numerical gradient helper ───────────────────────────────────

function numericalGrad(f, A, eps = 1e-3) {
  const n = A.shape[A.shape.length - 1]
  const data = A.arraySync()
  const grad = tf.buffer(A.shape)

  for (let i = 0; i < n; i++) {
    for (let j = 0; j <= i; j++) {
      const Aplus = data.map(row => [...row])
      Aplus[i][j] += eps
      Aplus[j][i] = Aplus[i][j]
      const Aminus = data.map(row => [...row])
      Aminus[i][j] -= eps
      Aminus[j][i] = Aminus[i][j]

      const tPlus = tf.tensor2d(Aplus)
      const tMinus = tf.tensor2d(Aminus)
      const vPlus = f(tPlus).dataSync()[0]
      const vMinus = f(tMinus).dataSync()[0]

      let g = (vPlus - vMinus) / (2 * eps)
      if (i !== j) g /= 2
      grad.set(g, i, j)
      if (i !== j) grad.set(g, j, i)

      tPlus.dispose(); tMinus.dispose()
    }
  }

  return grad.toTensor()
}
